[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cdp-connection"
version = "0.0.1"
description = "Basic example demonstrating CDP connection with Intuned"
authors = [{ name = "Intuned", email = "service@intunedhq.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
keywords = [
    "Python",
]
dependencies = [
    "playwright==1.56",
    "intuned-runtime==1.3.19",
    "intuned-browser==0.1.14",
    "httpx==0.28.1",
    "pydantic>=2.0.0",
]

[tool.uv]
package = false
