[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "browser-sdk-showcase"
version = "0.0.1"
description = "Showcase of Intuned Browser SDK helper functions for common automation tasks"
authors = [{ name = "Intuned", email = "service@intunedhq.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
keywords = [
    "Python",
    "intuned-browser-sdk",
]
dependencies = [
    "playwright==1.56",
    "intuned-runtime==1.3.17",
    "intuned-browser==0.1.13",
]

[tool.uv]
package = false
