[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stagehand-get-books"
version = "0.0.1"
description = "Using Stagehand with Intuned"
authors = [{ name = "Intuned", email = "service@intunedhq.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
keywords = [
    "Python",
    "AI",
    "Stagehand",
    "intuned-browser-sdk",
    "intuned-runtime-sdk",
    "intuned-runtime-sdk-setup-context-hook",
]
dependencies = [
    "playwright==1.56",
    "intuned-runtime==1.3.18",
    "intuned-browser==0.1.14",
    "anthropic~=0.75.0",
    "python-dateutil~=2.9.0",
    "httpx~=0.28.1",
    "stagehand~=0.5.8",
]

[tool.uv]
package = false
